# 1. PUERTO DEL MICROSERVICIO
server.port=8084

# 2. NOMBRE PARA EUREKA
spring.application.name=ms-usuario

# 3. CONEXIÓN A LA BASE DE DATOS
spring.datasource.url=jdbc:mysql://localhost:3306/bd_usuario?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# 4. CONFIGURACIÓN DE HIBERNATE
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# 5. CONEXIÓN A EUREKA SERVER
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/