# 1. EL PUERTO (Cámbialo para que no choque con el Gateway)
server.port=8085

# 2. EL NOMBRE DEL SERVICIO (Para que Eureka lo encuentre)
spring.application.name=ms-pago

# 3. CONEXIÓN A LA BASE DE DATOS (AQUÍ ESTÁ LA SOLUCIÓN AL ERROR)
# Cambia "pagos_db" por el nombre de la base de datos que hayan creado en MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/bd_pago?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# 4. HIBERNATE / JPA (Para que cree las tablas automáticamente)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# 5. CONEXIÓN A EUREKA
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/