# Puerto del microservicio
server.port=8086

# Nombre del microservicio para Eureka
spring.application.name=ms-ruta

# Conexion a la Base de Datos MySQL
spring.datasource.url=jdbc:mysql://mysql:3306/bd_ruta?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuracion de JPA e Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Conexion con Eureka Server
eureka.client.service-url.defaultZone=http://eureka:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# Configuracion de Swagger
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html